# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98aee5dced6514832c376bb1db224275d8c8f54ab9fbc85d46f0cf43ba9cc5a5a75fb80e8881d8049f640b98c1e9ddf56f094897e6b107ff11c3f87226dce90e

test:
  secret_key_base: ca74fff8d028cacb81118cb81c5df447d9eb84e77d72ea828cad47b89bec24365df8f0c3d8383800182c4f2356b96dd0cf3a5bd5378570147962459f145d4356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
